export const FETCH_PROPERTIES = 'FETCH_PROPERTIES';
export const FETCH_SAVED_PROPERTIES = 'FETCH_SAVED_PROPERTIES';
export const SAVE_PROPERTY = 'SAVE_PROPERTY';
export const REMOVE_PROPERTY = 'REMOVE_PROPERTY';


